bamboo-server:
    build: bamboo-server
    ports:
        - 8085:8085
        - 54663:54663
    links:
        - postgres
    environment:
        BAMBOO_VERSION: ${BAMBOO_VERSION}
        BAMBOO_HOME: /home/bamboo
        BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    volumes_from:
        - bamboo-data

bamboo-data:
    image: busybox
    tty: true
    volumes:
        - /home/bamboo

postgres:
    image: postgres:latest
    ports:
        - 15432:5432
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_DB: bamboo
        POSTGRES_USER: bamboo
        POSTGRES_PASSWORD: bamboo
    tty: true
    stdin_open: true
    volumes_from:
        - postgres-data

postgres-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/postgresql/data/pgdata

bamboo-agent:
    build: bamboo-agent
    links:
        - bamboo-server
    environment:
        BAMBOO_VERSION: ${BAMBOO_VERSION}
        BAMBOO_SERVER: bamboo-server
        BAMBOO_SERVER_PORT: 8085
        PACKAGES: "mc htop"
        no_proxy: bamboo-server
